### ISSUE TITLE
Not working with Win X 1803

### ISSUE THREAD

**Issue by wirecatz** [sampalmer/set-default-browser#10]
Hi, the Windows 10 build 1803 seems to have broken the tool. When run, it opens default app settings, and displays a message saying, "Didn't find all of the following extensions and protocols: .htm, .html, .http, .https." The default browser isn't changed.

**Comment by sampalmer** [comment]
@wirecatz, thanks for reporting this. I just tested it on my computer and got the same result.

I'm deprecating this tool because [Christoph Kolbicz has written a better one](http://kolbi.cz/blog/?p=396). Mine uses UI automation and is therefore unreliable, whereas he claims that his writes directly to the Windows registry. I just tested his one out and it's working fine for me on Windows 10 build 1803.

**Comment by sampalmer** [comment]
It turns out that Windows 10 version 1803 no longer uses the classic control panel "Default Programs" screen. Now the only UI for this is the Windows 10 settings app, which cannot be automated silently. So the technique used by this app is no longer possible.

I've released an update (1.2.2) to specifically detect this and show a more useful error message.
